FROM node AS build

# Set working directory.
WORKDIR /sobering_madison_final_site

COPY package.json .

# Install dependencies.
RUN npm install

COPY . .

# Build app.
RUN npm run build

FROM nginx AS production

COPY --from=build /sobering_madison_final_site/build /usr/share/nginx/html