FROM node:14-alpine AS development
ENV NODE_ENV development

# Set working directory name.
WORKDIR /sobering_madison_final_site

COPY package.json .

# Install dependencies.
RUN npm install

COPY . .

# Expose port.
EXPOSE 5575

# Start the app
CMD ["npm", "start"]